changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fix 💊
      labels:
        - bug
    - title: Other Changes 🛠
      labels:
        - '*'
