export enum FirstFlavors {
  Floral = 'Floral',
  Fruity = 'Fruity',
  SourFermented = 'Sour/Fermented',
  GreenVegetative = 'Green/Vegetative',
  Other = 'Other',
  Roasted = 'Roasted',
  Spices = 'Spices',
  NuttyCocoa = 'Nutty/Cocoa',
  Sweet = 'Sweet',
}

export const FirstFlavorsColor = {
  [FirstFlavors.Floral]: '#DA0D68',
  [FirstFlavors.Fruity]: '#DA1D23',
  [FirstFlavors.SourFermented]: '#EBB40D',
  [FirstFlavors.GreenVegetative]: '#197A2F',
  [FirstFlavors.Other]: '#0AA3B5',
  [FirstFlavors.Roasted]: '#C94930',
  [FirstFlavors.Spices]: '#AD213E',
  [FirstFlavors.NuttyCocoa]: '#A87B64',
  [FirstFlavors.Sweet]: '#E65832',
};

export const FirstFlavorsCount = {
  [FirstFlavors.Floral]: 4,
  [FirstFlavors.Fruity]: 18,
  [FirstFlavors.SourFermented]: 10,
  [FirstFlavors.GreenVegetative]: 10,
  [FirstFlavors.Other]: 16,
  [FirstFlavors.Roasted]: 8,
  [FirstFlavors.Spices]: 6,
  [FirstFlavors.NuttyCocoa]: 5,
  [FirstFlavors.Sweet]: 8,
};

export const FirstFlavorsJpLabel = {
  [FirstFlavors.Floral]: '花',
  [FirstFlavors.Fruity]: 'フルーツ',
  [FirstFlavors.SourFermented]: '酸味 / 発酵',
  [FirstFlavors.GreenVegetative]: '野菜',
  [FirstFlavors.Other]: 'その他',
  [FirstFlavors.Roasted]: '焼き',
  [FirstFlavors.Spices]: '香辛料',
  [FirstFlavors.NuttyCocoa]: 'ナッツ / ココア',
  [FirstFlavors.Sweet]: '甘味',
};

export enum SecondFlavors {
  BlackTea = 'Black Tea',
  Floral = 'Floral',
  Berry = 'Berry',
  DriedFruit = 'Dried fruit',
  OtherFruit = 'Other fruit',
  CitrusFruit = 'Citrus fruit',
  Sour = 'Sour',
  AlcoholFermented = 'Alcohol/Fermented',
  OliveOil = 'Olive oil',
  Raw = 'Raw',
  GreenVegetative = 'Green/Vegetative',
  Beany = 'Beany',
  PaperyMusty = 'Papery/Musty',
  Chemical = 'Chemical',
  PipeTobacco = 'Pipe tobacco',
  Tobacco = 'Tobacco',
  Burnt = 'Burnt',
  Cereal = 'Cereal',
  Pungent = 'Pungent',
  Pepper = 'Pepper',
  BrownSpice = 'Brown spice',
  Nutty = 'Nutty',
  Cocoa = 'Cocoa',
  BrownSugar = 'Brown sugar',
  Vanilla = 'Vanilla',
  Vanillin = 'Vanillin',
  OverallSweet = 'Overall sweet',
  SweetAromatics = 'Sweet Aromatics',
}

export const SecondFlavorsColor = {
  [SecondFlavors.BlackTea]: '#975E6D',
  [SecondFlavors.Floral]: '#E0719C',
  [SecondFlavors.Berry]: '#DD4C51',
  [SecondFlavors.DriedFruit]: '#C94A44',
  [SecondFlavors.OtherFruit]: '#F2684C',
  [SecondFlavors.CitrusFruit]: '#F7A129',
  [SecondFlavors.Sour]: '#E1C315',
  [SecondFlavors.AlcoholFermented]: '#B09733',
  [SecondFlavors.OliveOil]: '#A2B028',
  [SecondFlavors.Raw]: '#708933',
  [SecondFlavors.GreenVegetative]: '#3AA255',
  [SecondFlavors.Beany]: '#5E9A80',
  [SecondFlavors.PaperyMusty]: '#9DB2B7',
  [SecondFlavors.Chemical]: '#76C0CB',
  [SecondFlavors.PipeTobacco]: '#CAA465',
  [SecondFlavors.Tobacco]: '#DFBD7E',
  [SecondFlavors.Burnt]: '#BE8663',
  [SecondFlavors.Cereal]: '#DDAF61',
  [SecondFlavors.Pungent]: '#794652',
  [SecondFlavors.Pepper]: '#CC3C42',
  [SecondFlavors.BrownSpice]: '#B14D57',
  [SecondFlavors.Nutty]: '#C78869',
  [SecondFlavors.Cocoa]: '#BB764C',
  [SecondFlavors.BrownSugar]: '#D45A59',
  [SecondFlavors.Vanilla]: '#F89A80',
  [SecondFlavors.Vanillin]: '#F37674',
  [SecondFlavors.OverallSweet]: '#E75B68',
  [SecondFlavors.SweetAromatics]: '#D0545F',
};

export const SecondFlavorsCount = {
  [SecondFlavors.BlackTea]: 1,
  [SecondFlavors.Floral]: 3,
  [SecondFlavors.Berry]: 4,
  [SecondFlavors.DriedFruit]: 2,
  [SecondFlavors.OtherFruit]: 8,
  [SecondFlavors.CitrusFruit]: 4,
  [SecondFlavors.Sour]: 6,
  [SecondFlavors.AlcoholFermented]: 4,
  [SecondFlavors.OliveOil]: 1,
  [SecondFlavors.Raw]: 1,
  [SecondFlavors.GreenVegetative]: 7,
  [SecondFlavors.Beany]: 1,
  [SecondFlavors.PaperyMusty]: 10,
  [SecondFlavors.Chemical]: 6,
  [SecondFlavors.PipeTobacco]: 1,
  [SecondFlavors.Tobacco]: 1,
  [SecondFlavors.Burnt]: 4,
  [SecondFlavors.Cereal]: 2,
  [SecondFlavors.Pungent]: 1,
  [SecondFlavors.Pepper]: 1,
  [SecondFlavors.BrownSpice]: 4,
  [SecondFlavors.Nutty]: 3,
  [SecondFlavors.Cocoa]: 2,
  [SecondFlavors.BrownSugar]: 4,
  [SecondFlavors.Vanilla]: 1,
  [SecondFlavors.Vanillin]: 1,
  [SecondFlavors.OverallSweet]: 1,
  [SecondFlavors.SweetAromatics]: 1,
};

export const SecondFlavorsJpLabel = {
  [SecondFlavors.BlackTea]: '紅茶',
  [SecondFlavors.Floral]: '花',
  [SecondFlavors.Berry]: 'ベリー',
  [SecondFlavors.DriedFruit]: 'ドライフルーツ',
  [SecondFlavors.OtherFruit]: 'その他の果実',
  [SecondFlavors.CitrusFruit]: '柑橘類',
  [SecondFlavors.Sour]: '酸味',
  [SecondFlavors.AlcoholFermented]: '酒 / 発酵',
  [SecondFlavors.OliveOil]: 'オリーブオイル',
  [SecondFlavors.Raw]: '生野菜',
  [SecondFlavors.GreenVegetative]: '植物 / 野菜',
  [SecondFlavors.Beany]: '豆臭い',
  [SecondFlavors.PaperyMusty]: '紙 / カビ',
  [SecondFlavors.Chemical]: '化学薬品',
  [SecondFlavors.PipeTobacco]: 'パイプタバコ',
  [SecondFlavors.Tobacco]: 'タバコ',
  [SecondFlavors.Burnt]: '焦げ臭',
  [SecondFlavors.Cereal]: '穀物',
  [SecondFlavors.Pungent]: 'コショウ',
  [SecondFlavors.Pepper]: '唐辛子',
  [SecondFlavors.BrownSpice]: '香辛料',
  [SecondFlavors.Nutty]: 'ナッツ',
  [SecondFlavors.Cocoa]: 'ココア',
  [SecondFlavors.BrownSugar]: '黒砂糖',
  [SecondFlavors.Vanilla]: 'バニラ',
  [SecondFlavors.Vanillin]: 'バニラエッセンス',
  [SecondFlavors.OverallSweet]: '総合的な甘味',
  [SecondFlavors.SweetAromatics]: '甘い香り',
};

export enum ThirdFlavors {
  BlackTea = 'Black Tea',
  Chamomile = 'Chamomile',
  Rose = 'Rose',
  Jasmine = 'Jasmine',
  Blackberry = 'Blackberry',
  Raspberry = 'Raspberry',
  Blueberry = 'Blueberry',
  Strawberry = 'Strawberry',
  Raisin = 'Raisin',
  Prune = 'Prune',
  Coconut = 'Coconut',
  Cherry = 'Cherry',
  Pomegranate = 'Pomegranate',
  Pineapple = 'Pineapple',
  Grape = 'Grape',
  Apple = 'Apple',
  Peach = 'Peach',
  Pear = 'Pear',
  Grapefruit = 'Grapefruit',
  Orange = 'Orange',
  Lemon = 'Lemon',
  Lime = 'Lime',
  SourAromatics = 'Sour aromatics',
  AceticAcid = 'Acetic acid',
  ButyricAcid = 'Butyric acid',
  IsovalericAcid = 'Isovaleric acid',
  CitricAcid = 'Citric acid',
  MalicAcid = 'Malic acid',
  Winey = 'Winey',
  Whiskey = 'Whiskey',
  Fermented = 'Fermented',
  Overripe = 'Overripe',
  OliveOil = 'Olive oil',
  Raw = 'Raw',
  UnderRipe = 'Under-ripe',
  Peapod = 'Peapod',
  Fresh = 'Fresh',
  DarkGreen = 'Dark green',
  Vegetative = 'Vegetative',
  HayLike = 'Hay-like',
  HerbLike = 'Herb-like',
  Beany = 'Beany',
  Stale = 'Stale',
  Cardboard = 'Cardboard',
  Papery = 'Papery',
  Woody = 'Woody',
  MoldyDamp = 'Moldy/Damp',
  MustyDusty = 'Musty/Dusty',
  MustyEarthy = 'Musty/Earthy',
  Animalic = 'Animalic',
  MeatyBrothy = 'Meaty/Brothy',
  Phenolic = 'Phenolic',
  Bitter = 'Bitter',
  Salty = 'Salty',
  Medicinal = 'Medicinal',
  Petroleum = 'Petroleum',
  Skunky = 'Skunky',
  Rubber = 'Rubber',
  PipeTobacco = 'Pipe tobacco',
  Tobacco = 'Tobacco',
  Acrid = 'Acrid',
  Ashy = 'Ashy',
  Smoky = 'Smoky',
  BrownRoast = 'Brown, Roast',
  Grain = 'Grain',
  Malt = 'Malt',
  Pungent = 'Pungent',
  Pepper = 'Pepper',
  Anise = 'Anise',
  Nutmeg = 'Nutmeg',
  Cinnamon = 'Cinnamon',
  Clove = 'Clove',
  Peanuts = 'Peanuts',
  Hazelnut = 'Hazelnut',
  Almond = 'Almond',
  Chocolate = 'Chocolate',
  DarkChocolat = 'Dark chocolate',
  Molasses = 'Molasses',
  MappleSyrup = 'Mapple syrup',
  Caramelized = 'Caramelized',
  Honey = 'Honey',
  Vanilla = 'Vanilla',
  Vanillin = 'Vanillin',
  OverallSweet = 'Overall sweet',
  SweetAromatics = 'Sweet Aromatics',
}

export const ThirdFlavorsColor = {
  [ThirdFlavors.BlackTea]: 'transparent',
  [ThirdFlavors.Chamomile]: '#F99E1B',
  [ThirdFlavors.Rose]: '#EF5A78',
  [ThirdFlavors.Jasmine]: '#F7F1BD',
  [ThirdFlavors.Blackberry]: '#3E0317',
  [ThirdFlavors.Raspberry]: '#E52968',
  [ThirdFlavors.Blueberry]: '#6469B0',
  [ThirdFlavors.Strawberry]: '#EF2D36',
  [ThirdFlavors.Raisin]: '#B53B54',
  [ThirdFlavors.Prune]: '#A5446F',
  [ThirdFlavors.Coconut]: '#D07C36',
  [ThirdFlavors.Cherry]: '#E73451',
  [ThirdFlavors.Pomegranate]: '#E65656',
  [ThirdFlavors.Pineapple]: '#F89A1C',
  [ThirdFlavors.Grape]: '#AEB92C',
  [ThirdFlavors.Apple]: '#4EB947',
  [ThirdFlavors.Peach]: '#F68A5C',
  [ThirdFlavors.Pear]: '#BAA635',
  [ThirdFlavors.Grapefruit]: '#F26355',
  [ThirdFlavors.Orange]: '#E2631E',
  [ThirdFlavors.Lemon]: '#FDE402',
  [ThirdFlavors.Lime]: '#7EB138',
  [ThirdFlavors.SourAromatics]: '#9EA718',
  [ThirdFlavors.AceticAcid]: '#94A770',
  [ThirdFlavors.ButyricAcid]: '#D0B34F',
  [ThirdFlavors.IsovalericAcid]: '#8EB646',
  [ThirdFlavors.CitricAcid]: '#FAEF08',
  [ThirdFlavors.MalicAcid]: '#C1BA09',
  [ThirdFlavors.Winey]: '#8F1B53',
  [ThirdFlavors.Whiskey]: '#B34039',
  [ThirdFlavors.Fermented]: '#BA9232',
  [ThirdFlavors.Overripe]: '#8B6439',
  [ThirdFlavors.OliveOil]: 'transparent',
  [ThirdFlavors.Raw]: 'transparent',
  [ThirdFlavors.UnderRipe]: '#A2BC2B',
  [ThirdFlavors.Peapod]: '#62AA3C',
  [ThirdFlavors.Fresh]: '#03A653',
  [ThirdFlavors.DarkGreen]: '#048549',
  [ThirdFlavors.Vegetative]: '#27B44B',
  [ThirdFlavors.HayLike]: '#A3A830',
  [ThirdFlavors.HerbLike]: '#7AC141',
  [ThirdFlavors.Beany]: 'transparent',
  [ThirdFlavors.Stale]: '#8B8C90',
  [ThirdFlavors.Cardboard]: '#BDB175',
  [ThirdFlavors.Papery]: '#FEFEF4',
  [ThirdFlavors.Woody]: '#744F02',
  [ThirdFlavors.MoldyDamp]: '#A3A36F',
  [ThirdFlavors.MustyDusty]: '#C9B583',
  [ThirdFlavors.MustyEarthy]: '#988847',
  [ThirdFlavors.Animalic]: '#9D977F',
  [ThirdFlavors.MeatyBrothy]: '#CC7B6A',
  [ThirdFlavors.Phenolic]: '#DB646A',
  [ThirdFlavors.Bitter]: '#80A89D',
  [ThirdFlavors.Salty]: '#DEF2FD',
  [ThirdFlavors.Medicinal]: '#7A9BAE',
  [ThirdFlavors.Petroleum]: '#039FB8',
  [ThirdFlavors.Skunky]: '#5E777B',
  [ThirdFlavors.Rubber]: '#120C0C',
  [ThirdFlavors.PipeTobacco]: 'transparent',
  [ThirdFlavors.Tobacco]: 'transparent',
  [ThirdFlavors.Acrid]: '#B9A449',
  [ThirdFlavors.Ashy]: '#899893',
  [ThirdFlavors.Smoky]: '#A1743B',
  [ThirdFlavors.BrownRoast]: '#894810',
  [ThirdFlavors.Grain]: '#B7906F',
  [ThirdFlavors.Malt]: '#EB9D5E',
  [ThirdFlavors.Pungent]: 'transparent',
  [ThirdFlavors.Pepper]: 'transparent',
  [ThirdFlavors.Anise]: '#C78935',
  [ThirdFlavors.Nutmeg]: '#8C292C',
  [ThirdFlavors.Cinnamon]: '#E5762E',
  [ThirdFlavors.Clove]: '#A16C5A',
  [ThirdFlavors.Peanuts]: '#D4AD13',
  [ThirdFlavors.Hazelnut]: '#9D5433',
  [ThirdFlavors.Almond]: '#C89F83',
  [ThirdFlavors.Chocolate]: '#692A19',
  [ThirdFlavors.DarkChocolat]: '#470603',
  [ThirdFlavors.Molasses]: '#310C0F',
  [ThirdFlavors.MappleSyrup]: '#AE341F',
  [ThirdFlavors.Caramelized]: '#D78823',
  [ThirdFlavors.Honey]: '#DA5C1F',
  [ThirdFlavors.Vanilla]: 'transparent',
  [ThirdFlavors.Vanillin]: 'transparent',
  [ThirdFlavors.OverallSweet]: 'transparent',
  [ThirdFlavors.SweetAromatics]: 'transparent',
};

export const ThirdFlavorsJpLabel = {
  [ThirdFlavors.BlackTea]: '紅茶',
  [ThirdFlavors.Chamomile]: 'カモミール',
  [ThirdFlavors.Rose]: 'ローズ',
  [ThirdFlavors.Jasmine]: 'ジャスミン',
  [ThirdFlavors.Blackberry]: 'ブラックベリー',
  [ThirdFlavors.Raspberry]: 'ラズベリー',
  [ThirdFlavors.Blueberry]: 'ブルーベリー',
  [ThirdFlavors.Strawberry]: 'ストロベリー',
  [ThirdFlavors.Raisin]: 'レーズン',
  [ThirdFlavors.Prune]: 'プルーン',
  [ThirdFlavors.Coconut]: 'ココナッツ',
  [ThirdFlavors.Cherry]: 'チェリー',
  [ThirdFlavors.Pomegranate]: 'ザクロ',
  [ThirdFlavors.Pineapple]: 'パイナップル',
  [ThirdFlavors.Grape]: 'マスカット',
  [ThirdFlavors.Apple]: '青りんご',
  [ThirdFlavors.Peach]: '桃',
  [ThirdFlavors.Pear]: '洋梨',
  [ThirdFlavors.Grapefruit]: 'グレープフルーツ',
  [ThirdFlavors.Orange]: 'オレンジ',
  [ThirdFlavors.Lemon]: 'レモン',
  [ThirdFlavors.Lime]: 'ライム',
  [ThirdFlavors.SourAromatics]: '酸っぱい香り',
  [ThirdFlavors.AceticAcid]: '酢',
  [ThirdFlavors.ButyricAcid]: '銀杏臭い',
  [ThirdFlavors.IsovalericAcid]: '汗・足のにおい',
  [ThirdFlavors.CitricAcid]: 'クエン酸',
  [ThirdFlavors.MalicAcid]: 'リンゴ酸',
  [ThirdFlavors.Winey]: '赤ワイン',
  [ThirdFlavors.Whiskey]: 'ウィスキー',
  [ThirdFlavors.Fermented]: '発酵',
  [ThirdFlavors.Overripe]: '発酵しすぎ',
  [ThirdFlavors.OliveOil]: 'オリーブオイル',
  [ThirdFlavors.Raw]: '生野菜',
  [ThirdFlavors.UnderRipe]: '未成熟な野菜',
  [ThirdFlavors.Peapod]: 'さやえんどう',
  [ThirdFlavors.Fresh]: '生鮮野菜',
  [ThirdFlavors.DarkGreen]: 'ホウレンソウ',
  [ThirdFlavors.Vegetative]: '植物',
  [ThirdFlavors.HayLike]: '干し草',
  [ThirdFlavors.HerbLike]: 'ハーブ',
  [ThirdFlavors.Beany]: '豆臭い',
  [ThirdFlavors.Stale]: 'カビたパン',
  [ThirdFlavors.Cardboard]: '段ボール',
  [ThirdFlavors.Papery]: '紙',
  [ThirdFlavors.Woody]: '木材',
  [ThirdFlavors.MoldyDamp]: 'カビ / 湿気',
  [ThirdFlavors.MustyDusty]: 'カビ臭い埃',
  [ThirdFlavors.MustyEarthy]: 'カビ臭い土',
  [ThirdFlavors.Animalic]: '獣臭',
  [ThirdFlavors.MeatyBrothy]: 'ブイヨン',
  [ThirdFlavors.Phenolic]: '防腐剤',
  [ThirdFlavors.Bitter]: '苦い薬',
  [ThirdFlavors.Salty]: '塩素',
  [ThirdFlavors.Medicinal]: '消毒薬',
  [ThirdFlavors.Petroleum]: 'ガソリン',
  [ThirdFlavors.Skunky]: 'スカンクの悪臭',
  [ThirdFlavors.Rubber]: 'ゴム',
  [ThirdFlavors.PipeTobacco]: 'パイプタバコ',
  [ThirdFlavors.Tobacco]: 'タバコ',
  [ThirdFlavors.Acrid]: '燃えたゴム臭',
  [ThirdFlavors.Ashy]: '灰っぽい',
  [ThirdFlavors.Smoky]: '煙',
  [ThirdFlavors.BrownRoast]: '焦げ臭',
  [ThirdFlavors.Grain]: '穀物',
  [ThirdFlavors.Malt]: '麦芽',
  [ThirdFlavors.Pungent]: 'コショウ',
  [ThirdFlavors.Pepper]: '唐辛子',
  [ThirdFlavors.Anise]: 'アニス',
  [ThirdFlavors.Nutmeg]: 'ナツメグ',
  [ThirdFlavors.Cinnamon]: 'シナモン',
  [ThirdFlavors.Clove]: 'クローブ',
  [ThirdFlavors.Peanuts]: 'ピーナッツ',
  [ThirdFlavors.Hazelnut]: 'ヘーゼルナッツ',
  [ThirdFlavors.Almond]: 'アーモンド',
  [ThirdFlavors.Chocolate]: 'チョコレート',
  [ThirdFlavors.DarkChocolat]: 'ダークチョコレート',
  [ThirdFlavors.Molasses]: 'シロップ',
  [ThirdFlavors.MappleSyrup]: 'メープルシロップ',
  [ThirdFlavors.Caramelized]: 'キャラメリゼ',
  [ThirdFlavors.Honey]: 'ハチミツ',
  [ThirdFlavors.Vanilla]: 'バニラ',
  [ThirdFlavors.Vanillin]: 'バニラエッセンス',
  [ThirdFlavors.OverallSweet]: '総合的な甘味',
  [ThirdFlavors.SweetAromatics]: '甘い香り',
};

export type Flavor = FirstFlavors | SecondFlavors | ThirdFlavors;
export const FlavorJpLabel = {
  ...FirstFlavorsJpLabel,
  ...SecondFlavorsJpLabel,
  ...ThirdFlavorsJpLabel,
};

export const FirstFlavorStructures = {
  [FirstFlavors.Floral]: [SecondFlavors.BlackTea, SecondFlavors.Floral],
  [FirstFlavors.Fruity]: [
    SecondFlavors.Berry,
    SecondFlavors.DriedFruit,
    SecondFlavors.OtherFruit,
    SecondFlavors.CitrusFruit,
  ],
  [FirstFlavors.SourFermented]: [
    SecondFlavors.Sour,
    SecondFlavors.AlcoholFermented,
  ],
  [FirstFlavors.GreenVegetative]: [
    SecondFlavors.OliveOil,
    SecondFlavors.Raw,
    SecondFlavors.GreenVegetative,
    SecondFlavors.Beany,
  ],
  [FirstFlavors.Other]: [SecondFlavors.PaperyMusty, SecondFlavors.Chemical],
  [FirstFlavors.Roasted]: [
    SecondFlavors.PipeTobacco,
    SecondFlavors.Tobacco,
    SecondFlavors.Burnt,
    SecondFlavors.Cereal,
  ],
  [FirstFlavors.Spices]: [
    SecondFlavors.Pungent,
    SecondFlavors.Pepper,
    SecondFlavors.BrownSpice,
  ],
  [FirstFlavors.NuttyCocoa]: [SecondFlavors.Nutty, SecondFlavors.Cocoa],
  [FirstFlavors.Sweet]: [
    SecondFlavors.BrownSugar,
    SecondFlavors.Vanilla,
    SecondFlavors.Vanillin,
    SecondFlavors.OverallSweet,
    SecondFlavors.SweetAromatics,
  ],
};

export const SecondFlavorStructures = {
  [SecondFlavors.BlackTea]: [],
  [SecondFlavors.Floral]: [
    ThirdFlavors.Chamomile,
    ThirdFlavors.Rose,
    ThirdFlavors.Jasmine,
  ],
  [SecondFlavors.Berry]: [
    ThirdFlavors.Blackberry,
    ThirdFlavors.Raspberry,
    ThirdFlavors.Blueberry,
    ThirdFlavors.Strawberry,
  ],
  [SecondFlavors.DriedFruit]: [ThirdFlavors.Raisin, ThirdFlavors.Prune],
  [SecondFlavors.OtherFruit]: [
    ThirdFlavors.Coconut,
    ThirdFlavors.Cherry,
    ThirdFlavors.Pomegranate,
    ThirdFlavors.Pineapple,
    ThirdFlavors.Grape,
    ThirdFlavors.Apple,
    ThirdFlavors.Peach,
    ThirdFlavors.Pear,
  ],
  [SecondFlavors.CitrusFruit]: [
    ThirdFlavors.Grapefruit,
    ThirdFlavors.Orange,
    ThirdFlavors.Lemon,
    ThirdFlavors.Lime,
  ],
  [SecondFlavors.Sour]: [
    ThirdFlavors.SourAromatics,
    ThirdFlavors.AceticAcid,
    ThirdFlavors.ButyricAcid,
    ThirdFlavors.IsovalericAcid,
    ThirdFlavors.CitricAcid,
    ThirdFlavors.MalicAcid,
  ],
  [SecondFlavors.AlcoholFermented]: [
    ThirdFlavors.Winey,
    ThirdFlavors.Whiskey,
    ThirdFlavors.Fermented,
    ThirdFlavors.Overripe,
  ],
  [SecondFlavors.OliveOil]: [],
  [SecondFlavors.Raw]: [],
  [SecondFlavors.GreenVegetative]: [
    ThirdFlavors.UnderRipe,
    ThirdFlavors.Peapod,
    ThirdFlavors.Fresh,
    ThirdFlavors.DarkGreen,
    ThirdFlavors.Vegetative,
    ThirdFlavors.HayLike,
    ThirdFlavors.HerbLike,
  ],
  [SecondFlavors.Beany]: [],
  [SecondFlavors.PaperyMusty]: [
    ThirdFlavors.Stale,
    ThirdFlavors.Cardboard,
    ThirdFlavors.Papery,
    ThirdFlavors.Woody,
    ThirdFlavors.MoldyDamp,
    ThirdFlavors.MustyDusty,
    ThirdFlavors.MustyEarthy,
    ThirdFlavors.Animalic,
    ThirdFlavors.MeatyBrothy,
    ThirdFlavors.Phenolic,
  ],
  [SecondFlavors.Chemical]: [
    ThirdFlavors.Bitter,
    ThirdFlavors.Salty,
    ThirdFlavors.Medicinal,
    ThirdFlavors.Petroleum,
    ThirdFlavors.Skunky,
    ThirdFlavors.Rubber,
  ],
  [SecondFlavors.PipeTobacco]: [],
  [SecondFlavors.Tobacco]: [],
  [SecondFlavors.Burnt]: [
    ThirdFlavors.Acrid,
    ThirdFlavors.Ashy,
    ThirdFlavors.Smoky,
    ThirdFlavors.BrownRoast,
  ],
  [SecondFlavors.Cereal]: [ThirdFlavors.Grain, ThirdFlavors.Malt],
  [SecondFlavors.Pungent]: [],
  [SecondFlavors.Pepper]: [],
  [SecondFlavors.BrownSpice]: [
    ThirdFlavors.Anise,
    ThirdFlavors.Nutmeg,
    ThirdFlavors.Cinnamon,
    ThirdFlavors.Clove,
  ],
  [SecondFlavors.Nutty]: [
    ThirdFlavors.Peanuts,
    ThirdFlavors.Hazelnut,
    ThirdFlavors.Almond,
  ],
  [SecondFlavors.Cocoa]: [ThirdFlavors.Chocolate, ThirdFlavors.DarkChocolat],
  [SecondFlavors.BrownSugar]: [
    ThirdFlavors.Molasses,
    ThirdFlavors.MappleSyrup,
    ThirdFlavors.Caramelized,
    ThirdFlavors.Honey,
  ],
  [SecondFlavors.Vanilla]: [],
  [SecondFlavors.Vanillin]: [],
  [SecondFlavors.OverallSweet]: [],
  [SecondFlavors.SweetAromatics]: [],
};

export const firstItems = Object.values(FirstFlavors).map((flavor) => {
  return {
    value: FirstFlavorsCount[flavor],
    color: FirstFlavorsColor[flavor],
    flavor: flavor,
  };
});
export const secondItems = Object.values(SecondFlavors).map((flavor) => {
  return {
    value: SecondFlavorsCount[flavor],
    color: SecondFlavorsColor[flavor],
    flavor: flavor,
  };
});
export const thirdItems = Object.values(ThirdFlavors).map((flavor) => {
  return {
    value: 1,
    color: ThirdFlavorsColor[flavor],
    flavor: flavor,
  };
});
